// <auto-generated />
using EFCore.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Repo.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    partial class EmpresaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore.Domain.Empresa", b =>
                {
                    b.Property<int>("EmpCod")
                        .HasColumnType("int")
                        .HasMaxLength(8);

                    b.Property<string>("EmpCpfCnpj")
                        .HasColumnType("VARCHAR(18)");

                    b.Property<string>("EmpFan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpRaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpSts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCod");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("EFCore.Domain.Filial", b =>
                {
                    b.Property<int>("EmpCod")
                        .HasColumnType("int");

                    b.Property<int>("FilCod")
                        .HasColumnType("int");

                    b.Property<string>("FilFan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilRaz")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCod", "FilCod");

                    b.ToTable("Filial");
                });

            modelBuilder.Entity("EFCore.Domain.Pessoa", b =>
                {
                    b.Property<int>("EmpCod")
                        .HasColumnType("int");

                    b.Property<int>("PesCod")
                        .HasColumnType("int");

                    b.Property<string>("PesCpfCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesFan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesRaz")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCod", "PesCod");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("EFCore.Domain.Produto", b =>
                {
                    b.Property<int>("EmpCod")
                        .HasColumnType("int");

                    b.Property<int>("ProCod")
                        .HasColumnType("int");

                    b.Property<string>("ProNcm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProObs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCod", "ProCod");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("EFCore.Domain.Usuario", b =>
                {
                    b.Property<int>("UsuCod")
                        .HasColumnType("int");

                    b.Property<string>("UsuNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuSts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuTip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuCod");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("EFCore.Domain.UsuarioEmpresas", b =>
                {
                    b.Property<int>("UsuCod")
                        .HasColumnType("int");

                    b.Property<int>("EmpCod")
                        .HasColumnType("int");

                    b.HasKey("UsuCod", "EmpCod");

                    b.ToTable("UsuarioEmpresas");
                });
#pragma warning restore 612, 618
        }
    }
}
