// <auto-generated />
using Holtz_PDV_EFCore.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Holtz_PDV_EFCore.WebAPI.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20200623012156_createTableUsuario")]
    partial class createTableUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Holtz_PDV_EFCore.WebAPI.Models.Empresa", b =>
                {
                    b.Property<int>("EmpCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpCpfCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpFan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpRaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpSts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCod");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Holtz_PDV_EFCore.WebAPI.Models.Filial", b =>
                {
                    b.Property<int>("EmpCod")
                        .HasColumnType("int");

                    b.Property<int>("FilCod")
                        .HasColumnType("int");

                    b.HasKey("EmpCod", "FilCod");

                    b.ToTable("Filial");
                });

            modelBuilder.Entity("Holtz_PDV_EFCore.WebAPI.Models.Pessoa", b =>
                {
                    b.Property<int>("EmpCod")
                        .HasColumnType("int");

                    b.Property<int>("PesCod")
                        .HasColumnType("int");

                    b.Property<string>("PesCpfCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesFan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesRaz")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCod", "PesCod");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Holtz_PDV_EFCore.WebAPI.Models.Produto", b =>
                {
                    b.Property<int>("EmpCod")
                        .HasColumnType("int");

                    b.Property<int>("ProCod")
                        .HasColumnType("int");

                    b.Property<string>("ProNcm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProObs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCod", "ProCod");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Holtz_PDV_EFCore.WebAPI.Models.Usuario", b =>
                {
                    b.Property<int>("UsuCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UsuNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuSts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuTip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuCod");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
